# Generated by Django 5.0 on 2024-01-11 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0004_alter_cart_pid_alter_cart_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
